services:
  server:
    image: canebaycomputers/cbc:nginx-php8
    container_name: cbc-laravel-php8
    entrypoint: [ "bash", "-c", "sleep 5 && nginx && supervisord && php-fpm8.2 -F"]
    volumes:
      - .:/usr/share/nginx/html
    networks:
      default:
        ipv4_address: 10.2.0.31

networks:
  default:
    external: true
    name: cbc-docker-stack_vpcbr
