services:
  server:
    build: ./cbc-docker-php8-nginx
    image: cbc-docker-php8-nginx
    container_name: cbc-laravel-php8
    entrypoint: [ "bash", "-c", "sleep 5 && nginx && supervisord && php-fpm8.2 -F"]
    volumes:
      - .:/usr/share/nginx/html
      - ./cbc-docker-php8-nginx/ssl:/etc/nginx/certs
      - ./cbc-docker-php8-nginx/nginx/site.conf:/etc/nginx/sites-enabled/default
      - ./cbc-docker-php8-nginx/supervisor/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
    networks:
      default:
        ipv4_address: 10.2.0.31

networks:
  default:
    external: true
    name: cbc-docker-stack_vpcbr
